# Generated by Django 3.2.5 on 2021-07-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientTestimonies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_full_name', models.CharField(help_text='The legal full name of the client.', max_length=120, null=True, verbose_name='Client Full Name')),
                ('client_comment', models.TextField(help_text='The Client Comment.', null=True, verbose_name='Client Comment')),
                ('client_position', models.CharField(help_text='The Client Position.', max_length=50, null=True, verbose_name='Client Position')),
                ('client_image', models.ImageField(default='image.png', help_text='The Client Image.', null=True, upload_to='client_image/', verbose_name='Client Image')),
            ],
            options={
                'verbose_name': 'Client Feedback',
                'verbose_name_plural': 'Client Feedback',
            },
        ),
    ]
