# Generated by Django 3.2.5 on 2021-08-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.CharField(help_text='client FAQ questions and answers.', max_length=500, null=True, verbose_name='Customers Questions')),
                ('answers', models.TextField(help_text='Customers Answers.', null=True, verbose_name='Customers Answers')),
            ],
            options={
                'verbose_name': 'FAQ questions and answers',
                'verbose_name_plural': 'FAQ questions and answers',
            },
        ),
    ]
